default:
  image: 'rust:1.38-alpine'

stages:
  - build
  - test
  - cover
  - examples
  - doc

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
    - $CARGO_HOME
    - target/

build:
  stage: build
  script:
    - "rustc --version && cargo --version"
    - cargo build --verbose

build latest:
  stage: build
  image: 'rust:alpine'
  script:
    - "rustc --version && cargo --version"
    - cargo build --verbose

test:
  stage: test
  script:
    - "rustc --version && cargo --version"
    - cargo test --verbose

cover:
  stage: cover
  image: 'rust:latest'
  script:
    - "rustc --version && cargo --version"
    - cargo install --root $CARGO_HOME grcov
    - $CARGO_HOME/grcov build/ -t lcov > lcov.info
  artifacts:
    paths:
      - lcov.info

examples:
  stage: examples
  before_script:
    - apk add --update make
  script:
    - "rustc --version && cargo --version"
    - make all_examples

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - cp -R target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=automatica/index.html">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
