default:
  image: 'rust:1.38-alpine'

stages:
  - build
  - test
  - examples
  - doc

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
    - $CARGO_HOME
    - target/

build:
  stage: build
  script:
    - "rustc --version && cargo --version"
    - cargo build --verbose

build latest:
  stage: build
  image: 'rust:alpine'
  script:
    - "rustc --version && cargo --version"
    - cargo build --verbose

test:
  stage: test
  script:
    - "rustc --version && cargo --version"
    - cargo test --verbose

cover:
  stage: test
  image: 'rust:latest'
  before_script:
    - "apt-get update && apt-get -y install libssl-dev pkg-config cmake zlib1g-dev"
    - cargo install cargo-tarpaulin
    - rm -rf cargo/registry
  script:
    - "rustc --version && cargo --version"
    - cargo tarpaulin -v --exclude-files cargo -o Html
  coverage: '/\d+\.\d+/ coverage'
  artifacts:
    paths:
      - tarpaulin-report.html

examples:
  stage: examples
  before_script:
    - apk add --update make
  script:
    - "rustc --version && cargo --version"
    - make all_examples

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - cp -R target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=automatica/index.html">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
