[package]
name = "automatica"
version = "0.6.0"
authors = ["daingun <>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
num-complex = "0.2"
nalgebra = "0.18.0"
ndarray = "0.12.1"
approx = "0.3.2"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.8"
